# -*- coding: utf-8 -*-
"""classifierML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d54IZQr0LPoWcdQiJBcFtg9Zd1jT5Cg8

https://eloquentarduino.github.io/2019/11/how-to-train-a-classifier-in-scikit-learn/
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)
# %cd /content/gdrive//MyDrive/SEECS/ESD/edgeML-3
!ls

!pip install -U scikit-learn
!pip install -U micromlgen

import numpy as np
from os.path import basename
from glob import glob
from sklearn.svm import SVC
from micromlgen import port
from sklearn.model_selection import train_test_split

def load_features():
    dataset = None
    classmap = {}
    for class_idx, filename in enumerate(glob('/content/gdrive/MyDrive/SEECS/ESD/edgeML-3/wav2csv/*Water.csv')):
        class_name = basename(filename)[:-4]
        classmap[class_idx] = class_name
        samples = np.loadtxt(filename, dtype=float, delimiter=',')
        labels = np.ones((len(samples), 1)) * class_idx
        samples = np.hstack((samples, labels))
        dataset = samples if dataset is None else np.vstack((dataset, samples))
    return dataset, classmap

np.random.seed(0)
dataset, classmap = load_features()
X, y = dataset[:, :-1], dataset[:, -1]
# this line is for testing your accuracy only: once you're satisfied with the results, set test_size to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

clf = SVC(kernel='poly',degree = 1, gamma=0.001, C = 1000)
clf.fit(X_train, y_train)

from micromlgen import port

c_code = port(clf, classmap=classmap)
print(c_code)

with open('tensorflow_model.h', 'w') as file:
      file.write(c_code)