# -*- coding: utf-8 -*-
"""wav2csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HEkF3jZicI5XOWHxhE0mzPLC5kI6sgEd
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)
# %cd /content/gdrive//MyDrive/SEECS/ESD/edgeML-3/wav2csv
!ls

import wave
import csv
import os

def pouringWater(wav_file):
  # Open the wav file
  with wave.open(wav_file, 'r') as wav:
    # Read the wave file's frame rate and number of channels
    frame_rate = wav.getframerate()
    num_channels = wav.getnchannels()

    # Read the wave file's sample width and compute the number of bytes per sample
    sample_width = wav.getsampwidth()
    bytes_per_sample = sample_width * num_channels

    # Read the wave file's number of frames and compute the duration of the file
    num_frames = wav.getnframes()
    duration = num_frames / frame_rate

    # Initialize a list to hold the waveform data
    waveform_data = []

    # Read the wave file's frames and append them to the waveform data list
    for i in range(num_frames):
      frame = wav.readframes(1)
      waveform_data.append(int.from_bytes(frame, byteorder='little', signed=True))

    # Open a CSV file to write the waveform data to
    with open('pouringWater.csv', 'a', newline='\n') as csv_file:
      # Create a CSV writer
      writer = csv.writer(csv_file)
      print(waveform_data)
      # Write the waveform data to the CSV file
      writer.writerow(waveform_data)

def dropWater(wav_file):
  # Open the wav file
  with wave.open(wav_file, 'r') as wav:
    # Read the wave file's frame rate and number of channels
    frame_rate = wav.getframerate()
    num_channels = wav.getnchannels()

    # Read the wave file's sample width and compute the number of bytes per sample
    sample_width = wav.getsampwidth()
    bytes_per_sample = sample_width * num_channels

    # Read the wave file's number of frames and compute the duration of the file
    num_frames = wav.getnframes()
    duration = num_frames / frame_rate

    # Initialize a list to hold the waveform data
    waveform_data = []

    # Read the wave file's frames and append them to the waveform data list
    for i in range(num_frames):
      frame = wav.readframes(1)
      waveform_data.append(int.from_bytes(frame, byteorder='little', signed=True))

    # Open a CSV file to write the waveform data to
    with open('dropWater.csv', 'a', newline='\n') as csv_file:
      # Create a CSV writer
      writer = csv.writer(csv_file)
      print(waveform_data)
      # Write the waveform data to the CSV file
      writer.writerow(waveform_data)

def others(wav_file):
  # Open the wav file
  with wave.open(wav_file, 'r') as wav:
    # Read the wave file's frame rate and number of channels
    frame_rate = wav.getframerate()
    num_channels = wav.getnchannels()

    # Read the wave file's sample width and compute the number of bytes per sample
    sample_width = wav.getsampwidth()
    bytes_per_sample = sample_width * num_channels

    # Read the wave file's number of frames and compute the duration of the file
    num_frames = wav.getnframes()
    duration = num_frames / frame_rate

    # Initialize a list to hold the waveform data
    waveform_data = []

    # Read the wave file's frames and append them to the waveform data list
    for i in range(num_frames):
      frame = wav.readframes(1)
      waveform_data.append(int.from_bytes(frame, byteorder='little', signed=True))

    # Open a CSV file to write the waveform data to
    with open('others.csv', 'a', newline='\n') as csv_file:
      # Create a CSV writer
      writer = csv.writer(csv_file)
      print(waveform_data)
      # Write the waveform data to the CSV file
      writer.writerow(waveform_data)

file_path = '/content/gdrive/MyDrive/SEECS/ESD/edgeML-3/ESC-50/audio/'
for file in os.listdir(file_path):
  print(file)
  if file.endswith("17.wav"):
    pouringWater(file_path + file)
  elif file.endswith("15.wav"):
    dropWater(file_path + file)
  else:
    others(file_path + file)

